"""Pure, bounded Experience evidence contracts for R12."""

from kagya.experience.records import (
    EXPERIENCE_MAX_REVISIONS,
    EXPERIENCE_MAX_REVISION,
    EXPERIENCE_MAX_EVENT_SEQUENCE,
    EXPERIENCE_SCHEMA_VERSION,
    ExperienceAppraisalEvidence,
    ExperienceEmotionContributions,
    ExperienceEmotionProjection,
    ExperienceLifecycle,
    ExperienceMeasurementEvidence,
    ExperienceRecord,
    ExperienceRevisionOperation,
    ExperienceRevisionReason,
    ExperienceRevisionRecord,
    calculate_subjective_salience,
    canonical_experience_payload,
    canonical_experience_revision_payload,
    compute_subjective_salience,
    experience_revision_digest,
    experience_record_digest,
    subjective_salience,
)

__all__ = [
    "EXPERIENCE_MAX_REVISIONS",
    "EXPERIENCE_MAX_REVISION",
    "EXPERIENCE_MAX_EVENT_SEQUENCE",
    "EXPERIENCE_SCHEMA_VERSION",
    "ExperienceAppraisalEvidence",
    "ExperienceEmotionContributions",
    "ExperienceEmotionProjection",
    "ExperienceLifecycle",
    "ExperienceMeasurementEvidence",
    "ExperienceRecord",
    "ExperienceRevisionOperation",
    "ExperienceRevisionReason",
    "ExperienceRevisionRecord",
    "calculate_subjective_salience",
    "canonical_experience_payload",
    "canonical_experience_revision_payload",
    "compute_subjective_salience",
    "experience_revision_digest",
    "experience_record_digest",
    "subjective_salience",
]
