"""Learning and adapter lifecycle helpers for PROJECT-KAGYA."""

from kagya.learning.adapter_evaluator import (
    AdapterEvaluationDecision,
    AdapterEvaluationResult,
    AdapterEvaluator,
)
from kagya.learning.adapter_registry import (
    ActivationEligibility,
    ActivationEligibilityReason,
    AdapterEntry,
    AdapterRegistry,
    AdapterStatus,
)
from kagya.learning.adapter_runtime import (
    AdapterActivationRecord,
    AdapterRuntimeManager,
    RuntimeAdapterState,
)
from kagya.learning.behavioral_evaluation import (
    ActionAttempt,
    BehavioralEvaluationManifest,
    BehavioralDimension,
    BehavioralEvaluator,
    BehavioralEvaluatorSpec,
    BehavioralInvariant,
    BehavioralScenario,
    BehavioralTrace,
    BehavioralRuntimeKind,
    ExternalObservation,
    HardGate,
    InvariantKind,
    PublicBehaviorClass,
    ReproducibilityMetadata,
    StateTransition,
    TransitionExpectation,
    TransitionKind,
    proactive_outbox_scenarios,
    agency_attribution_scenarios,
    counterfactual_simulation_scenarios,
    fixture_set_hash,
    scenario_fixture_hash,
)
from kagya.learning.subject_behavioral_suite import (
    DeterministicSubjectRunner,
    run_deterministic_subject_evaluation,
    subject_completion_scenarios,
)
from kagya.learning.dream_dataset_generator import (
    DreamDatasetGenerator,
    DreamDatasetRecord,
    format_training_text,
)
from kagya.learning.eval_sets import EvalCase, EvalSet, load_eval_sets
from kagya.learning.qlora_trainer import (
    QloraTrainer,
    QloraTrainingError,
    QloraTrainingResult,
)
from kagya.learning.sleep_consolidation import SleepCycleManager, SleepCycleResult

__all__ = [
    "ActionAttempt",
    "ActivationEligibility",
    "ActivationEligibilityReason",
    "BehavioralEvaluationManifest",
    "AdapterEntry",
    "AdapterEvaluationDecision",
    "AdapterEvaluationResult",
    "AdapterEvaluator",
    "AdapterRegistry",
    "AdapterRuntimeManager",
    "AdapterActivationRecord",
    "RuntimeAdapterState",
    "AdapterStatus",
    "BehavioralDimension",
    "BehavioralEvaluator",
    "BehavioralEvaluatorSpec",
    "BehavioralInvariant",
    "BehavioralRuntimeKind",
    "BehavioralScenario",
    "BehavioralTrace",
    "DreamDatasetGenerator",
    "DeterministicSubjectRunner",
    "DreamDatasetRecord",
    "EvalCase",
    "EvalSet",
    "ExternalObservation",
    "HardGate",
    "InvariantKind",
    "QloraTrainer",
    "QloraTrainingError",
    "QloraTrainingResult",
    "PublicBehaviorClass",
    "ReproducibilityMetadata",
    "SleepCycleManager",
    "SleepCycleResult",
    "StateTransition",
    "TransitionExpectation",
    "TransitionKind",
    "format_training_text",
    "fixture_set_hash",
    "load_eval_sets",
    "run_deterministic_subject_evaluation",
    "scenario_fixture_hash",
    "subject_completion_scenarios",
    "proactive_outbox_scenarios",
    "agency_attribution_scenarios",
    "counterfactual_simulation_scenarios",
]
