"""Learning and adapter lifecycle helpers for PROJECT-KAGYA."""

from kagya.learning.adapter_evaluator import (
    AdapterEvaluationDecision,
    AdapterEvaluationResult,
    AdapterEvaluator,
)
from kagya.learning.adapter_registry import (
    ActivationEligibility,
    ActivationEligibilityReason,
    BehavioralEvidenceStatus,
    AdapterEntry,
    AdapterRegistry,
    AdapterStatus,
)
from kagya.learning.adapter_runtime import (
    AdapterActivationRecord,
    AdapterRuntimeManager,
    RuntimeAdapterState,
)
from kagya.learning.behavioral_evaluation import (
    ActionAttempt,
    BehavioralEvaluationManifest,
    BehavioralDimension,
    BehavioralEvaluator,
    BehavioralEvaluatorSpec,
    BehavioralInvariant,
    BehavioralScenario,
    BehavioralTrace,
    BehavioralRuntimeKind,
    CoverageStatus,
    RuntimeBehaviorClassifier,
    RuntimeBehaviorObservation,
    ExternalObservation,
    HardGate,
    InvariantKind,
    PublicBehaviorClass,
    ReproducibilityMetadata,
    StateTransition,
    TransitionExpectation,
    TransitionKind,
    proactive_outbox_scenarios,
    agency_attribution_scenarios,
    counterfactual_simulation_scenarios,
    fixture_set_hash,
    scenario_fixture_hash,
)
from kagya.learning.behavioral_coverage import (
    BEHAVIORAL_COVERAGE_MANIFEST,
    BehavioralCoverageEvaluation,
    BehavioralCoverageManifest,
    BehavioralCoverageRequirement,
    BehavioralHardGateRequirement,
    evaluate_behavioral_coverage,
)
from kagya.learning.subject_behavioral_suite import (
    DeterministicSubjectRunner,
    SyntheticTraceRunner,
    run_deterministic_subject_evaluation,
    subject_completion_scenarios,
)
from kagya.learning.behavioral_artifacts import (
    BehavioralArtifactRecord,
    BehavioralArtifactStatus,
    BehavioralArtifactStore,
)
from kagya.learning.runtime_behavioral_harness import (
    AuthoritativeTransitionCollector,
    ControlledClock,
    ControlledToolEnvironment,
    DeterministicRuntimeProvider,
    FailureInjector,
    InjectedRuntimeFailure,
    SubjectRuntimeHarness,
)
from kagya.learning.runtime_behavioral_runner import (
    DeterministicRuntimeRunner,
    RuntimeBehavioralRunner,
    deterministic_runtime_scenarios,
    run_deterministic_runtime_evaluation,
)
from kagya.learning.real_model_runtime_behavioral import (
    load_real_model_provider_pair,
    run_real_model_runtime_evaluation,
)
from kagya.learning.dream_dataset_generator import (
    DreamDatasetGenerator,
    DreamDatasetRecord,
    format_training_text,
)
from kagya.learning.eval_sets import EvalCase, EvalSet, load_eval_sets
from kagya.learning.qlora_trainer import (
    QloraTrainer,
    QloraTrainingError,
    QloraTrainingResult,
)
from kagya.learning.sleep_consolidation import SleepCycleManager, SleepCycleResult

__all__ = [
    "ActionAttempt",
    "ActivationEligibility",
    "ActivationEligibilityReason",
    "BehavioralEvidenceStatus",
    "BehavioralEvaluationManifest",
    "BehavioralArtifactRecord",
    "BehavioralArtifactStatus",
    "BehavioralArtifactStore",
    "AdapterEntry",
    "AdapterEvaluationDecision",
    "AdapterEvaluationResult",
    "AdapterEvaluator",
    "AdapterRegistry",
    "AdapterRuntimeManager",
    "AdapterActivationRecord",
    "RuntimeAdapterState",
    "AdapterStatus",
    "BehavioralDimension",
    "BehavioralEvaluator",
    "BehavioralEvaluatorSpec",
    "BehavioralInvariant",
    "BehavioralRuntimeKind",
    "CoverageStatus",
    "BEHAVIORAL_COVERAGE_MANIFEST",
    "BehavioralCoverageEvaluation",
    "BehavioralCoverageManifest",
    "BehavioralCoverageRequirement",
    "BehavioralHardGateRequirement",
    "evaluate_behavioral_coverage",
    "RuntimeBehaviorClassifier",
    "RuntimeBehaviorObservation",
    "BehavioralScenario",
    "BehavioralTrace",
    "AuthoritativeTransitionCollector",
    "ControlledClock",
    "ControlledToolEnvironment",
    "DeterministicRuntimeProvider",
    "DeterministicRuntimeRunner",
    "RuntimeBehavioralRunner",
    "FailureInjector",
    "InjectedRuntimeFailure",
    "SubjectRuntimeHarness",
    "DreamDatasetGenerator",
    "DeterministicSubjectRunner",
    "SyntheticTraceRunner",
    "DreamDatasetRecord",
    "EvalCase",
    "EvalSet",
    "ExternalObservation",
    "HardGate",
    "InvariantKind",
    "QloraTrainer",
    "QloraTrainingError",
    "QloraTrainingResult",
    "PublicBehaviorClass",
    "ReproducibilityMetadata",
    "SleepCycleManager",
    "SleepCycleResult",
    "StateTransition",
    "TransitionExpectation",
    "TransitionKind",
    "format_training_text",
    "fixture_set_hash",
    "load_eval_sets",
    "run_deterministic_subject_evaluation",
    "run_deterministic_runtime_evaluation",
    "run_real_model_runtime_evaluation",
    "load_real_model_provider_pair",
    "deterministic_runtime_scenarios",
    "scenario_fixture_hash",
    "subject_completion_scenarios",
    "proactive_outbox_scenarios",
    "agency_attribution_scenarios",
    "counterfactual_simulation_scenarios",
]
